# Curated RSS defaults with weights (1-3)
sources:
  - id: arxiv-cs-ne
    weight: 2
    url: https://export.arxiv.org/rss/cs.NE
  - id: arxiv-cs-lg
    weight: 2
    url: https://export.arxiv.org/rss/cs.LG
  - id: arxiv-q-bio-nc
    weight: 2
    url: https://export.arxiv.org/rss/q-bio.NC
  - id: biorxiv-neuro
    weight: 2
    url: https://www.biorxiv.org/collection/neuroscience/rss.xml
  - id: nature-neuroscience
    weight: 3
    url: https://www.nature.com/neuro/rss/current.xml
  - id: elife-neuroscience
    weight: 2
    url: https://elifesciences.org/subjects/neuroscience/rss.xml
  - id: pnas-neuroscience
    weight: 2
    url: https://www.pnas.org/rss/subject/neuroscience.xml
  - id: nih-director-blog
    weight: 2
    url: https://directorsblog.nih.gov/feed/
  - id: mit-techreview-ai
    weight: 1
    url: https://www.technologyreview.com/feed/tag/artificial-intelligence/

