# Curated RSS defaults with weights (tiers: society journals=3 > high-signal blogs=2 > press=1)
sources:
  - id: arxiv-cs-ne
    weight: 2  # preprint server (signal varies)
    url: https://export.arxiv.org/rss/cs.NE
  - id: arxiv-cs-lg
    weight: 2  # preprint server
    url: https://export.arxiv.org/rss/cs.LG
  - id: arxiv-q-bio-nc
    weight: 2  # preprint server
    url: https://export.arxiv.org/rss/q-bio.NC
  - id: biorxiv-neuro
    weight: 2  # preprint server (bio)
    url: https://www.biorxiv.org/collection/neuroscience/rss.xml
  - id: nature-neuroscience
    weight: 3  # society journal / high editorial standards
    url: https://www.nature.com/neuro/rss/current.xml
  - id: elife-neuroscience
    weight: 3  # society/peer-reviewed open science
    url: https://elifesciences.org/subjects/neuroscience/rss.xml
  - id: pnas-neuroscience
    weight: 3  # society journal
    url: https://www.pnas.org/rss/subject/neuroscience.xml
  - id: nih-director-blog
    weight: 2  # high-signal blog
    url: https://directorsblog.nih.gov/feed/
  - id: mit-techreview-ai
    weight: 1  # press/coverage
    url: https://www.technologyreview.com/feed/tag/artificial-intelligence/
