name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install project [dev]
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pytest with coverage
        env:
          EMBED_OFFLINE: '1'
          LLM_OFFLINE: '1'
          PYTHONHASHSEED: '1'
        run: |
          pytest --maxfail=1 -q --cov=pipeline --cov-report=xml

