name: Discovery Scaffold

on:
  workflow_dispatch:

jobs:
  discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Dry run discovery
        run: |
          python -m pipeline discover --window-days 60 --out artifacts --ipfs-fetch=false --store-to-db=false

